# Generated by Django 4.0.2 on 2022-03-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='books')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
                ('publication', models.CharField(max_length=1000)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.books')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.content')),
            ],
        ),
    ]
